#!/usr/bin/env python3
"""Refresh the auto-generated token-savings snapshot in the READMEs.

Pulls live telemetry from the local tqmemory install via ``server_info_impl``
(read-only: it constructs a MemoryStore and reads on-disk stats, it never takes
the writer lock) and rewrites the block between the ``TQ-STATS:BEGIN`` /
``TQ-STATS:END`` markers in every README (English, Ukrainian, Russian).

The numbers are one machine's cumulative telemetry, presented as a transparent,
self-verifiable example rather than a synthetic benchmark. Regenerate whenever
you want the READMEs to reflect the current instance.

Usage:
    uv run python scripts/refresh_readme_stats.py            # rewrite in place
    uv run python scripts/refresh_readme_stats.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BEGIN = (
    "<!-- TQ-STATS:BEGIN (auto-generated by scripts/refresh_readme_stats.py "
    "— do not edit by hand) -->"
)
END = "<!-- TQ-STATS:END -->"

# locale -> README filename
READMES = {
    "en": "README.md",
    "uk": "README.uk.md",
    "ru": "README.ru.md",
}

# Per-locale wording. {tokens}/{searches}/{hydrations}/{per_retrieval}/{notes}/
# {blocks}/{quarantined}/{pending}/{version} are filled from live telemetry.
TEMPLATES = {
    "en": """### 📈 It measures its own savings — see for yourself

Turbo Quant Memory doesn't just *claim* to save tokens — every install keeps a running tally you can read anytime with `server_info()` (field `usage_stats.headline`). The savings are yours to verify, not ours to promise.

**Live snapshot from a real developer instance (v{version}):**

| What the memory did | Number |
| :--- | :--- |
| 🔢 Input tokens saved (cumulative) | **≈ {tokens}** and counting |
| 🔁 Retrievals served | **{searches}** searches + **{hydrations}** deep hydrations |
| 📉 Average saved per retrieval | **≈ {per_retrieval} tokens** |
| 📚 Knowledge under management | **{notes}** active notes + **{blocks}** indexed code blocks |
| 🛡️ Integrity | **{quarantined}** corrupted records · **{pending}** pending migrations |

> These are one machine's cumulative numbers, not a synthetic benchmark — your own counter starts at zero and grows as your agent works. Run `server_info()` on your install to see your real figure.""",
    "uk": """### 📈 Пам'ять сама рахує свою економію — переконайтеся особисто

Turbo Quant Memory не просто *обіцяє* економити токени — кожна інсталяція веде живий підрахунок, який ви будь-коли зчитаєте через `server_info()` (поле `usage_stats.headline`). Цю економію ви перевіряєте самі, а не вірите нам на слово.

**Живий зріз з реального інстансу розробника (v{version}):**

| Що зробила пам'ять | Число |
| :--- | :--- |
| 🔢 Заощаджено вхідних токенів (сумарно) | **≈ {tokens}** і зростає |
| 🔁 Оброблено запитів | **{searches}** пошуків + **{hydrations}** глибоких підвантажень |
| 📉 Середня економія на запит | **≈ {per_retrieval} токенів** |
| 📚 Знань під керуванням | **{notes}** активних нотаток + **{blocks}** проіндексованих блоків коду |
| 🛡️ Цілісність | **{quarantined}** пошкоджених записів · **{pending}** незавершених міграцій |

> Це сумарні числа однієї машини, а не синтетичний бенчмарк — ваш власний лічильник стартує з нуля й зростає в міру роботи агента. Запустіть `server_info()` на своїй інсталяції, щоб побачити свою реальну цифру.""",
    "ru": """### 📈 Память сама считает свою экономию — убедитесь лично

Turbo Quant Memory не просто *обещает* экономить токены — каждая установка ведёт живой подсчёт, который вы в любой момент прочитаете через `server_info()` (поле `usage_stats.headline`). Эту экономию вы проверяете сами, а не верите нам на слово.

**Живой срез с реального инстанса разработчика (v{version}):**

| Что сделала память | Число |
| :--- | :--- |
| 🔢 Сэкономлено входных токенов (суммарно) | **≈ {tokens}** и растёт |
| 🔁 Обработано запросов | **{searches}** поисков + **{hydrations}** глубоких подгрузок |
| 📉 Средняя экономия на запрос | **≈ {per_retrieval} токенов** |
| 📚 Знаний под управлением | **{notes}** активных заметок + **{blocks}** проиндексированных блоков кода |
| 🛡️ Целостность | **{quarantined}** повреждённых записей · **{pending}** незавершённых миграций |

> Это суммарные числа одной машины, а не синтетический бенчмарк — ваш собственный счётчик стартует с нуля и растёт по мере работы агента. Запустите `server_info()` на своей установке, чтобы увидеть свою реальную цифру.""",
}


def _round_to(value: int, step: int) -> int:
    if value <= 0:
        return 0
    return int(round(value / step) * step)


def _group(value: int, locale: str) -> str:
    """Thousands grouping: comma for English, space for uk/ru typography."""
    grouped = f"{value:,}"
    return grouped if locale == "en" else grouped.replace(",", " ")


def gather_stats() -> dict[str, int | str]:
    """Read live, read-only telemetry from the local tqmemory install."""
    from turbo_memory_mcp import __version__
    from turbo_memory_mcp.server import server_info_impl

    info = server_info_impl(cwd=REPO_ROOT)
    totals = (info.get("usage_stats") or {}).get("totals") or {}
    storage = info.get("storage_stats") or {}
    project = storage.get("project") or {}
    global_ = storage.get("global") or {}
    migrations = info.get("migrations") or {}

    tokens_saved = int(totals.get("estimated_input_tokens_saved", 0))
    searches = int(totals.get("search_calls", 0))
    hydrations = int(totals.get("hydrate_calls", 0))
    per_retrieval = round(tokens_saved / searches) if searches else 0

    active_notes = int(project.get("note_count", 0)) + int(global_.get("note_count", 0))
    code_blocks = int(project.get("markdown_block_count", 0))
    quarantined = len(project.get("quarantined_notes") or []) + len(
        global_.get("quarantined_notes") or []
    )
    pending = 1 if migrations.get("pending", False) else 0

    return {
        "version": str(__version__),
        # ≈ values are rounded so they read as an honest approximation, not a
        # spuriously precise benchmark; exact counts stay exact.
        "tokens_saved": _round_to(tokens_saved, 10_000),
        "per_retrieval": _round_to(per_retrieval, 100),
        "searches": searches,
        "hydrations": hydrations,
        "active_notes": active_notes,
        "code_blocks": code_blocks,
        "quarantined": quarantined,
        "pending_migrations": pending,
    }


def render_block(locale: str, stats: dict[str, int | str]) -> str:
    return TEMPLATES[locale].format(
        version=stats["version"],
        tokens=_group(int(stats["tokens_saved"]), locale),
        per_retrieval=_group(int(stats["per_retrieval"]), locale),
        searches=_group(int(stats["searches"]), locale),
        hydrations=_group(int(stats["hydrations"]), locale),
        notes=_group(int(stats["active_notes"]), locale),
        blocks=_group(int(stats["code_blocks"]), locale),
        quarantined=stats["quarantined"],
        pending=stats["pending_migrations"],
    )


def apply_block(text: str, inner: str, *, readme: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(
            f"{readme}: markers {BEGIN!r} / {END!r} not found — add them once "
            "around the stats block before running this script."
        )
    replacement = f"{BEGIN}\n{inner}\n{END}"
    return pattern.sub(lambda _m: replacement, text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if any README is out of date.",
    )
    args = parser.parse_args()

    stats = gather_stats()

    stale: list[str] = []
    for locale, filename in READMES.items():
        path = REPO_ROOT / filename
        original = path.read_text(encoding="utf-8")
        updated = apply_block(original, render_block(locale, stats), readme=filename)
        if updated == original:
            continue
        stale.append(filename)
        if not args.check:
            path.write_text(updated, encoding="utf-8")

    if args.check:
        if stale:
            print("Stale README stats: " + ", ".join(stale))
            print("Run: uv run python scripts/refresh_readme_stats.py")
            return 1
        print("README stats are up to date.")
        return 0

    if stale:
        print(f"Updated stats in: {', '.join(stale)}")
    else:
        print("README stats already current — nothing to write.")
    print(
        f"  tokens≈{stats['tokens_saved']:,} · searches={stats['searches']} · "
        f"hydrations={stats['hydrations']} · notes={stats['active_notes']} · "
        f"blocks={stats['code_blocks']} · quarantined={stats['quarantined']} · "
        f"pending_migrations={stats['pending_migrations']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
